// Guide section definitions -- the fixed order for the MVP's five combined
// sections (see PROJECT_BRIEF.md > "Fixed Guide Format"). generateGuide.ts
// imports this to build the prompt and parse/order the single LLM response.
//
// the sixth section, "Uncertainties and Missing Information," isn't listed
// here - it's assembled from skippedFiles, not generated by the LLM.

type GuideSectionId = "overview" | "setup" | "running" | "structure" | "testing";

// title is the exact heading the LLM must produce: id is a stable key for 
// the post-MVP five-task verson to look up each section's own prompt.
type GuideSection = {
    id: GuideSectionId;
    title: string;
};

// Order here is the order sections appear in the guide. Single source of 
// truth for both the prompt builder and generateGuide.ts's parser
const GUIDE_SECTIONS: GuideSection[] = [
    { id: "overview", title: "Project Overview" },
    { id: "setup", title: "Setup / Installation" },
    { id: "running", title: "Running Locally" },
    { id: "structure", title: "Project Structure" },
    { id: "testing", title: "Testing" },
];

export { GUIDE_SECTIONS };
export type { GuideSectionId, GuideSection };
