// Guide section definitions -- the fixed order for the MVP's five combined
// sections (see PROJECT_BRIEF.md > "Fixed Guide Format"). prompts/mvpGuidePrompt.ts
// imports this to build the combined MVP prompt; generateGuide.ts uses it to order sections.
//
// the sixth section, "Uncertainties and Missing Information," isn't listed
// here - it's assembled from skippedFiles, not generated by the LLM.

type GuideSectionId = "overview" | "setup" | "running" | "structure" | "testing";

// title is the exact heading the LLM must produce: id is a stable key for
// the post-MVP five-task version to look up each section's own prompt.
type GuideSection = {
    id: GuideSectionId;
    title: string;
};

// Order here is the order sections appear in the guide. Single source of 
// truth for both the prompt builder and generateGuide.ts's parser
const GUIDE_SECTIONS: GuideSection[] = [
    { id: "overview", title: "Project Overview" },
    { id: "setup", title: "Setup / Installation" },
    { id: "running", title: "Running Locally" },
    { id: "structure", title: "Project Structure" },
    { id: "testing", title: "Testing" },
];

// Fixed per-section token budgets for evidence selection (see DECISIONS.md >
// "Token-Budgeted, Section-Scored Evidence Selection (Token Ceiling Fix)").
// A starting proposal, not a measured ceiling - revisit against a real
// target once one is agreed on.
const SECTION_BUDGETS: Record<GuideSectionId, number> = {
    overview: 12000,
    setup: 9000,
    running: 6000,
    structure: 21000,
    testing: 12000,
};

export { GUIDE_SECTIONS, SECTION_BUDGETS };
export type { GuideSectionId, GuideSection };
